// flow-typed signature: 458d0254705d8607bafbe6df10f7c39c
// flow-typed version: <<STUB>>/@commitlint/config-conventional_v7.3.1/flow_v0.91.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@commitlint/config-conventional'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@commitlint/config-conventional' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@commitlint/config-conventional/index' {
  declare module.exports: $Exports<'@commitlint/config-conventional'>;
}
declare module '@commitlint/config-conventional/index.js' {
  declare module.exports: $Exports<'@commitlint/config-conventional'>;
}
