// flow-typed signature: 07c17d39f4be907eb7f714886d83879c
// flow-typed version: <<STUB>>/babili-webpack-plugin_v0.1.2/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babili-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babili-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babili-webpack-plugin/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babili-webpack-plugin/lib/index.js' {
  declare module.exports: $Exports<'babili-webpack-plugin/lib/index'>;
}
