// flow-typed signature: e3dd0c32f4a9f87beed3052761c5df2f
// flow-typed version: <<STUB>>/eslint-plugin-no-loops_v0.3.0/flow_v0.91.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-no-loops'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-no-loops' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-no-loops/lib/no-loops' {
  declare module.exports: any;
}

declare module 'eslint-plugin-no-loops/tests/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-no-loops/index' {
  declare module.exports: $Exports<'eslint-plugin-no-loops'>;
}
declare module 'eslint-plugin-no-loops/index.js' {
  declare module.exports: $Exports<'eslint-plugin-no-loops'>;
}
declare module 'eslint-plugin-no-loops/lib/no-loops.js' {
  declare module.exports: $Exports<'eslint-plugin-no-loops/lib/no-loops'>;
}
declare module 'eslint-plugin-no-loops/tests/index.js' {
  declare module.exports: $Exports<'eslint-plugin-no-loops/tests/index'>;
}
