// flow-typed signature: 70108edc31d3a9561e8d012ba348381b
// flow-typed version: <<STUB>>/eslint-plugin-new-with-error_v2.0.0/flow_v0.91.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-new-with-error'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-new-with-error' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-new-with-error/lib/rules/new-with-error' {
  declare module.exports: any;
}

declare module 'eslint-plugin-new-with-error/tests/lib/rules/new-with-error' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-new-with-error/index' {
  declare module.exports: $Exports<'eslint-plugin-new-with-error'>;
}
declare module 'eslint-plugin-new-with-error/index.js' {
  declare module.exports: $Exports<'eslint-plugin-new-with-error'>;
}
declare module 'eslint-plugin-new-with-error/lib/rules/new-with-error.js' {
  declare module.exports: $Exports<'eslint-plugin-new-with-error/lib/rules/new-with-error'>;
}
declare module 'eslint-plugin-new-with-error/tests/lib/rules/new-with-error.js' {
  declare module.exports: $Exports<'eslint-plugin-new-with-error/tests/lib/rules/new-with-error'>;
}
