// flow-typed signature: 0af511524098dd79a3c56005da8d99a4
// flow-typed version: <<STUB>>/eslint-plugin-disable_v1.0.3/flow_v0.91.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-disable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-disable' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-disable/src/processor' {
  declare module.exports: any;
}

declare module 'eslint-plugin-disable/src/settings' {
  declare module.exports: any;
}

declare module 'eslint-plugin-disable/test/index.test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-disable/test/src/processor/inline.test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-disable/test/src/processor/inlineAllExcept.test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-disable/test/src/processor/processor.test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-disable/test/src/processor/settings.test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-disable/test/src/processor/settingsAllExcept.test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-disable/test/src/settings.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-disable/index' {
  declare module.exports: $Exports<'eslint-plugin-disable'>;
}
declare module 'eslint-plugin-disable/index.js' {
  declare module.exports: $Exports<'eslint-plugin-disable'>;
}
declare module 'eslint-plugin-disable/src/processor.js' {
  declare module.exports: $Exports<'eslint-plugin-disable/src/processor'>;
}
declare module 'eslint-plugin-disable/src/settings.js' {
  declare module.exports: $Exports<'eslint-plugin-disable/src/settings'>;
}
declare module 'eslint-plugin-disable/test/index.test.js' {
  declare module.exports: $Exports<'eslint-plugin-disable/test/index.test'>;
}
declare module 'eslint-plugin-disable/test/src/processor/inline.test.js' {
  declare module.exports: $Exports<'eslint-plugin-disable/test/src/processor/inline.test'>;
}
declare module 'eslint-plugin-disable/test/src/processor/inlineAllExcept.test.js' {
  declare module.exports: $Exports<'eslint-plugin-disable/test/src/processor/inlineAllExcept.test'>;
}
declare module 'eslint-plugin-disable/test/src/processor/processor.test.js' {
  declare module.exports: $Exports<'eslint-plugin-disable/test/src/processor/processor.test'>;
}
declare module 'eslint-plugin-disable/test/src/processor/settings.test.js' {
  declare module.exports: $Exports<'eslint-plugin-disable/test/src/processor/settings.test'>;
}
declare module 'eslint-plugin-disable/test/src/processor/settingsAllExcept.test.js' {
  declare module.exports: $Exports<'eslint-plugin-disable/test/src/processor/settingsAllExcept.test'>;
}
declare module 'eslint-plugin-disable/test/src/settings.test.js' {
  declare module.exports: $Exports<'eslint-plugin-disable/test/src/settings.test'>;
}
