// flow-typed signature: fae0229799fa71f24e1b76f19d2a9492
// flow-typed version: <<STUB>>/htmlescape_v1.1.1/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'htmlescape'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'htmlescape' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'htmlescape/htmlescape' {
  declare module.exports: any;
}

// Filename aliases
declare module 'htmlescape/htmlescape.js' {
  declare module.exports: $Exports<'htmlescape/htmlescape'>;
}
