// flow-typed signature: 47cd3a6b17262bff821a6e5e4f92b504
// flow-typed version: <<STUB>>/material-colors_v1.2.6/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'material-colors'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'material-colors' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'material-colors/dist/colors.es2015' {
  declare module.exports: any;
}

declare module 'material-colors/dist/colors' {
  declare module.exports: any;
}

declare module 'material-colors/test/fixtures/default-import' {
  declare module.exports: any;
}

declare module 'material-colors/test/fixtures/named-import' {
  declare module.exports: any;
}

declare module 'material-colors/test/fixtures/wildcard-import' {
  declare module.exports: any;
}

declare module 'material-colors/test/index' {
  declare module.exports: any;
}

declare module 'material-colors/test/module' {
  declare module.exports: any;
}

// Filename aliases
declare module 'material-colors/dist/colors.es2015.js' {
  declare module.exports: $Exports<'material-colors/dist/colors.es2015'>;
}
declare module 'material-colors/dist/colors.js' {
  declare module.exports: $Exports<'material-colors/dist/colors'>;
}
declare module 'material-colors/test/fixtures/default-import.js' {
  declare module.exports: $Exports<'material-colors/test/fixtures/default-import'>;
}
declare module 'material-colors/test/fixtures/named-import.js' {
  declare module.exports: $Exports<'material-colors/test/fixtures/named-import'>;
}
declare module 'material-colors/test/fixtures/wildcard-import.js' {
  declare module.exports: $Exports<'material-colors/test/fixtures/wildcard-import'>;
}
declare module 'material-colors/test/index.js' {
  declare module.exports: $Exports<'material-colors/test/index'>;
}
declare module 'material-colors/test/module.js' {
  declare module.exports: $Exports<'material-colors/test/module'>;
}
