// flow-typed signature: 30baf31abaac4619011f51170c24a9f5
// flow-typed version: <<STUB>>/react-facebook-pixel_v0.1.2/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-facebook-pixel'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-facebook-pixel' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-facebook-pixel/demo/index' {
  declare module.exports: any;
}

declare module 'react-facebook-pixel/dist/fb-pixel' {
  declare module.exports: any;
}

declare module 'react-facebook-pixel/src/index' {
  declare module.exports: any;
}

declare module 'react-facebook-pixel/webpack.config.dev' {
  declare module.exports: any;
}

declare module 'react-facebook-pixel/webpack.config.dist' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-facebook-pixel/demo/index.js' {
  declare module.exports: $Exports<'react-facebook-pixel/demo/index'>;
}
declare module 'react-facebook-pixel/dist/fb-pixel.js' {
  declare module.exports: $Exports<'react-facebook-pixel/dist/fb-pixel'>;
}
declare module 'react-facebook-pixel/src/index.js' {
  declare module.exports: $Exports<'react-facebook-pixel/src/index'>;
}
declare module 'react-facebook-pixel/webpack.config.dev.js' {
  declare module.exports: $Exports<'react-facebook-pixel/webpack.config.dev'>;
}
declare module 'react-facebook-pixel/webpack.config.dist.js' {
  declare module.exports: $Exports<'react-facebook-pixel/webpack.config.dist'>;
}
