// flow-typed signature: b32f639a6ef78bc55e652e4f32ba5d94
// flow-typed version: <<STUB>>/vegas_v2.4.4/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vegas'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vegas' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vegas/dist/vegas' {
  declare module.exports: any;
}

declare module 'vegas/dist/vegas.min' {
  declare module.exports: any;
}

declare module 'vegas/gulpfile' {
  declare module.exports: any;
}

declare module 'vegas/src/vegas' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vegas/dist/vegas.js' {
  declare module.exports: $Exports<'vegas/dist/vegas'>;
}
declare module 'vegas/dist/vegas.min.js' {
  declare module.exports: $Exports<'vegas/dist/vegas.min'>;
}
declare module 'vegas/gulpfile.js' {
  declare module.exports: $Exports<'vegas/gulpfile'>;
}
declare module 'vegas/src/vegas.js' {
  declare module.exports: $Exports<'vegas/src/vegas'>;
}
