// flow-typed signature: c1be7cc0584322e88f89a797f4625e27
// flow-typed version: <<STUB>>/@joncursi/eslint-config_v4.0.0/flow_v0.91.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@joncursi/eslint-config'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@joncursi/eslint-config' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@joncursi/eslint-config/commitlint.config' {
  declare module.exports: any;
}

declare module '@joncursi/eslint-config/intl' {
  declare module.exports: any;
}

declare module '@joncursi/eslint-config/prettier.config' {
  declare module.exports: any;
}

// Filename aliases
declare module '@joncursi/eslint-config/commitlint.config.js' {
  declare module.exports: $Exports<'@joncursi/eslint-config/commitlint.config'>;
}
declare module '@joncursi/eslint-config/index' {
  declare module.exports: $Exports<'@joncursi/eslint-config'>;
}
declare module '@joncursi/eslint-config/index.js' {
  declare module.exports: $Exports<'@joncursi/eslint-config'>;
}
declare module '@joncursi/eslint-config/intl.js' {
  declare module.exports: $Exports<'@joncursi/eslint-config/intl'>;
}
declare module '@joncursi/eslint-config/prettier.config.js' {
  declare module.exports: $Exports<'@joncursi/eslint-config/prettier.config'>;
}
